### ISSUE TITLE
Rename Repository

### ISSUE THREAD

**Issue by ErickSimoes** [Makerama/Arduino-Basico-ArduinoD18#1]
I recommend that this repository be renamed to a more suggestive name, like:
`Arduino-Basico-ArduinoD18`, ou `Workshop-Arduino-Basico-ArduinoD18`.

**Comment by OtacilioN** [comment]
I was thinking to do a repository to all contents in Arduino Day, and a folder inside to the Arduino Basico Workshop,  so all the contents from workshops and talks could be posted here. Is it better to create a repository just for the workshop instead of the event?

**Comment by OtacilioN** [comment]
I was thinking to do a repository to all contents in Arduino Day, and a folder inside to the Arduino Basico Workshop,  so all the contents from workshops and talks could be posted here. Is it better to create a repository just for the workshop instead of the event?

**Comment by OtacilioN** [comment]
What do you think about it @ErickSimoes ?

**Comment by ErickSimoes** [comment]
That would make everyone have to download the contents of all the workshops, which can make things a bit confusing.
It gets even more organized, but for didactic purposes I prefer to leave the projects separate.

**Comment by OtacilioN** [comment]
Done @ErickSimoes sorry for the delay. I Will finish the examples and post the slides today.

**Comment by ErickSimoes** [comment]
Nice!
Thank you very much!
